services:
  backend:
    build: ./backend  
    container_name: backend_service
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  frontend:
    build: ./frontend   
    container_name: frontend_service
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000