import os
import sys
from openai import OpenAI

class FeedbackGenerator:
    """
    A class to generate qualitative feedback for an essay using an LLM.
    """
    def __init__(self, api_key: str):
        """
        Initialises the FeedbackGenerator by setting up the OpenAI client.

        Args:
            api_key (str): The OpenAI API key passed from the main script.
        """
        if not api_key:
            raise ValueError("An API key must be provided to the FeedbackGenerator.", file=sys.stderr)
            
        try:
            self.client = OpenAI(api_key=api_key)
            # Test the connection to ensure the API key is valid.
            self.client.models.list() 
        except Exception as e:
            print(f"Error: Could not initialize OpenAI client. The API key may be invalid or expired: {e}")
            raise e

    def _construct_prompt(self, essay_text: str, rubric_scores: dict) -> list[dict]:
        """Helper method to build the prompt for the LLM."""
        system_prompt = "You are an encouraging and helpful English teacher. Your goal is to provide constructive, easy-to-understand feedback to an EFL (English as a Foreign Language) student."

        user_prompt = f"""
        Please provide feedback on the following essay based on its rubric scores.

        **Rubric Scores:**
        - Cohesion: {rubric_scores.get('cohesion', 'N/A')}/5
        - Syntax: {rubric_scores.get('syntax', 'N/A')}/5
        - Vocabulary: {rubric_scores.get('vocabulary', 'N/A')}/5
        - Phraseology: {rubric_scores.get('phraseology', 'N/A')}/5
        - Grammar: {rubric_scores.get('grammar', 'N/A')}/5
        - Conventions: {rubric_scores.get('conventions', 'N/A')}/5

        **Student's Essay:**
        ---
        {essay_text}
        ---

        **Instructions:**
        1.  Start with an encouraging comment that highlights an overall strength of the essay.
        2.  Based on the scores, identify one or two main strengths of the essay.
        3.  Based on the scores, identify the one or two most important areas for improvement.
        4.  Provide specific examples from the essay to illustrate your points.
        5.  Keep the language clear and simple for an English learner.
        6.  Format your response using Markdown for clear headings (e.g., "### Strengths", "### Areas for Improvement").
        """
        
        return [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]

    def generate_feedback(self, essay_text: str, rubric_scores: dict) -> str:
        """
        Generates feedback for a given essay and its rubric scores.

        Args:
            essay_text (str): The full text of the student's essay.
            rubric_scores (dict): A dictionary of quantitative scores.

        Returns:
            str: The qualitative feedback generated by the LLM.
        """
        messages = self._construct_prompt(essay_text, rubric_scores)
        
        print("Generating feedback with GPT-3.5 Turbo...", file=sys.stderr)
        try:
            response = self.client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=messages,
                temperature=0.7 
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"An error occurred while calling the OpenAI API: {e}", file=sys.stderr)
            return "Error: Could not generate feedback."