import os
import sys
from google import genai

class FeedbackGenerator:
    """
    A class to generate qualitative feedback for an essay using an LLM.
    """
    def __init__(self, api_key: str):
        """
        Initialises the FeedbackGenerator by setting up the Gemini client.

        Args:
            api_key (str): The Gemini API key passed from the main script.
        """
        if not api_key:
            raise ValueError("An API key must be provided to the FeedbackGenerator.")
            
        try:
            self.client = genai.Client(api_key=api_key)
            # Test the connection to ensure the API key is valid.
            self.client.models.list() 
        except Exception as e:
            print(f"Error: Could not initialise Gemini client. The API key may be invalid or expired: {e}", file=sys.stderr)
            raise e

    def _construct_prompt(self, essay_text: str, rubric_scores: dict, teacher: str) -> list[dict]:
        """Helper method to build the prompt for the LLM."""
        system_prompt = teacher
        user_prompt = f"""
        Please provide feedback on the following essay based on its rubric scores.

        **Rubric Scores:**
        - Cohesion: {rubric_scores.get('cohesion', 'N/A')}/10
        - Syntax: {rubric_scores.get('syntax', 'N/A')}/10
        - Vocabulary: {rubric_scores.get('vocabulary', 'N/A')}/10
        - Phraseology: {rubric_scores.get('phraseology', 'N/A')}/10
        - Grammar: {rubric_scores.get('grammar', 'N/A')}/10
        - Conventions: {rubric_scores.get('conventions', 'N/A')}/10

        **Student's Essay:**
        ---
        {essay_text}
        ---

        **Instructions:**
        1.  Start with a comment that highlights an overall strength of the essay.
        2.  Based on the scores, identify one or two main strengths of the essay.
        3.  Based on the scores, identify the one or two most important areas for improvement.
        4.  Provide specific examples from the essay to illustrate your points.
        5.  Keep the language clear and simple for an English learner.
        6.  Format your response using Markdown for clear headings (e.g., "### Strengths", "### Areas for Improvement").
        """
        
        return [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]

    def generate_feedback(self, essay_text: str, rubric_scores: dict, teacher:str) -> str:
        """
        Generates feedback for a given essay and its rubric scores.

        Args:
            essay_text (str): The full text of the student's essay.
            rubric_scores (dict): A dictionary of quantitative scores.
            teacher (str): Teacher personality prompt (user selects 'easy-going', 'medium', or 'super strict').

        Returns:
            str: The qualitative feedback generated by the LLM.
        """
        contents = self._construct_prompt(essay_text, rubric_scores, teacher)
        
        print("Generating feedback with Gemini 3 Flash...", file=sys.stderr)
        try:
            response = client.models.generate_content(
                model="gemini-3-flash-preview", 
                contents=contents, temperature=0.4)
            return response.text
        except Exception as e:
            print(f"An error occurred while calling the Gemini API: {e}", file=sys.stderr)
            return "Error: Could not generate feedback."